#ifndef HTSP_HTSPTAGS_H_
#define HTSP_HTSPTAGS_H_

#define HTSP_ID_API_VERSION "api_version"
#define HTSP_ID_CHALLENGE "challenge"
#define HTSP_ID_CHANNEL "channel"
#define HTSP_ID_CHANNEL_ICON "channelIcon"
#define HTSP_ID_CHANNEL_ID "channelId"
#define HTSP_ID_CHANNEL_NAME "channelName"
#define HTSP_ID_CHANNEL_NUMBER "channelNumber"
#define HTSP_ID_CHANNEL_NUMBER_MINOR "channelNumberMinor"
#define HTSP_ID_CLIENT_NAME "clientname"
#define HTSP_ID_CLIENT_VERSION "clientversion"
#define HTSP_ID_CREATOR "creator"
#define HTSP_ID_DAYS_OF_WEEK "daysOfWeek"
#define HTSP_ID_DIGEST "digest"
#define HTSP_ID_EPG "epg"
#define HTSP_ID_ENABLED "enabled"
#define HTSP_ID_HTSP_VERSION "htspversion"
#define HTSP_ID_ID "id"
#define HTSP_ID_LANGUAGE "language"
#define HTSP_ID_METHOD "method"
#define HTSP_ID_NAME "name"
#define HTSP_ID_NO_ACCESS "noaccess"
#define HTSP_ID_OWNER "owner"
#define HTSP_ID_PRIORITY "priority"
#define HTSP_ID_SERVER_CAPABILITY "servercapability"
#define HTSP_ID_SERVER_NAME "servername"
#define HTSP_ID_SERVER_VERSION "serverversion"
#define HTSP_ID_SERVICES "services"
#define HTSP_ID_START "start"
#define HTSP_ID_STOP "stop"
#define HTSP_ID_SUBTITLE "subtitle"
#define HTSP_ID_TAGS "tags"
#define HTSP_ID_TAG_ICON "tagIcon"
#define HTSP_ID_TAG_ID "tagId"
#define HTSP_ID_TAG_INDEX "tagIndex"
#define HTSP_ID_TAG_NAME "tagName"
#define HTSP_ID_TAG_TITLED_ICON "tagTitledIcon"
#define HTSP_ID_TITLE "title"
#define HTSP_ID_USERNAME "username"

#define HTSP_METHOD_AUTHENTICATE "authenticate"
#define HTSP_METHOD_AUTOREC_ENTRY_ADD "autorecEntryAdd"
#define HTSP_METHOD_CHANNEL_ADD "channelAdd"
#define HTSP_METHOD_DVR_ENTRY_ADD "dvrEntryAdd"
#define HTSP_METHOD_ENABLE_ASYNC_METADATA "enableAsyncMetadata"
#define HTSP_METHOD_HELLO "hello"
#define HTSP_METHOD_INITIAL_SYNC_COMPLETED "initialSyncCompleted"
#define HTSP_METHOD_TAG_ADD "tagAdd"
#define HTSP_METHOD_TAG_UPDATE "tagUpdate"

#endif /* HTSP_HTSPTAGS_H_ */
